### PR TITLE
Add upload-artifact to build script

### PR DESCRIPTION
**Pull request by DestroyerXyz**
This will upload the compiled binary to Github actions.

### CODE REVIEW

**Comment by DestroyerXyz** [comment]
I am also currently working on compiling for all platforms. Will create another PR for that.

**Comment by tkellogg** [comment]
@DestroyerXyz This looks like it uploads artifacts for every commit on PR and merge. Wouldn't that get noisy?

**Comment by DestroyerXyz** [comment]
It says inside the action, does not create a release or something.

**Comment by DestroyerXyz** [comment]
Added build for multiple platforms.
macOS binary doesn't work on arm64-macos because of some OpenSSL issue https://github.com/vorburger/MariaDB4j/issues/497.
Creating an arm64-macos binary is a cumbersome process because of signing requirements https://github.com/kotatogram/kotatogram-desktop/issues/278

**Review by tkellogg — APPROVED** [review]

**Comment by drupol** [comment]
Excellent, thanks for taking over on this. I had plan to do it, but got busy with life and work lately.

**Comment by DestroyerXyz** [comment]
You're welcome

**Comment by DestroyerXyz** [comment]
@tkellogg BTW, you can add [skip ci] to the beginning of a commit to skip ci like if updating the README for example.

**Pull request merged**
