### PR TITLE
Update for new install way!

### PR DESCRIPTION
**Pull request by MisileLab**
I published dura to crates.io.
Now can Install with `cargo install dura`!

### CODE REVIEW

**Review by tkellogg — APPROVED** [review]
This is great! When I started, I don't think this was possible, but I turned it into a library for testing purposes, so I guess that's changed. Do you think we can get this integrated into a release process?

**Comment by MisileLab** [comment]
hmm... probably can. just need a crates.io account token to publish. (you can save secretly in the project secret tab)

**Comment by tkellogg** [comment]
@MisileLab Can you please transfer ownership on crates.io to [me](https://crates.io/users/tkellogg)? thanks

**Comment by MisileLab** [comment]
> @MisileLab Can you please transfer ownership on crates.io to [me](https://crates.io/users/tkellogg)? thanks

I saw comment now lol, ok I'll transfer @tkellogg

**Pull request merged**
