### PR TITLE
Add flake files for development on Nixos.

### PR DESCRIPTION
**Pull request by drupol**
Hi,

I'm using those flake files to build a development environment for people using Nix.

Let me know if you're ok to include those files in the project (those could be used in Github actions to build the package automatically too)

### CODE REVIEW

**Comment by tkellogg** [comment]
@drupol What are flake files and is there another way to do this? (just trying to get familiar with it)

**Comment by drupol** [comment]
Ok, this is a long story :)

First read this page so you get the official documentation: https://nixos.wiki/wiki/Flakes

Flakes is to Nix what what Cargo is to Rust (with .toml and .lock). There is the same kind of stuff in other languages (nodejs, php, python...).
Basically anyone using Nixpgs either on Nixos or on another platform will be able to quickly hack into dura by running `nix develop .`.
Running this nix command will provide all the necessary Rust tools to be able to develop and run the tests locally.

This is what I'm using to do my first steps with Rust on my machine.

**Review by tkellogg — APPROVED** [review]
Seems like a good improvement

**Comment by drupol** [comment]
Cool great !!!

**Pull request merged**
